[project]
name = "roborover"
version = "0.1.0"
description = "RoboRover is a simple simulation of a toy robot on a tabletop, taking commands from the user to interact with the robot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.3.5",
]
